### ISSUE TITLE
name in edit profile is not prepopulated correctly

### ISSUE THREAD

**Issue by krishnasaurabh** [ramyasaimullapudi/WolfTrackPlus#21]
![image](https://user-images.githubusercontent.com/12223198/143691456-41e1dc6c-0035-4997-81c9-1a0fa87c2194.png)

**Comment by rhnprabhune** [comment]
Working on it

**Comment by rhnprabhune** [comment]
![image](https://user-images.githubusercontent.com/51504486/144160513-17c4e8d8-b411-4cd4-af02-4e92d5e35f58.png)

Hi @krishnasaurabh  The fix has been implemented. Raised a PR for this. Kindly approve

**Comment by rhnprabhune** [comment]
Fixed by #36
