### ISSUE TITLE
Clicking navbar logo "WolfTrack" logs out of the website

### ISSUE THREAD

**Issue by krishnasaurabh** [ramyasaimullapudi/WolfTrackPlus#5]
Going to / or clicking the navbar logo logs out the user.
it should take to the home page instead.
If the session is timed out/ invalidated then it should take to the login screen

**Comment by rhnprabhune** [comment]
Hi @krishnasaurabh . Were you able to find the root cause of this bug ?

**Comment by rhnprabhune** [comment]
I am working on this
