### ISSUE TITLE
Deploy website on AWS/ Heroku

### ISSUE THREAD

**Issue by krishnasaurabh** [ramyasaimullapudi/WolfTrackPlus#6]
Deploy the application on AWS/ Heroku to make it public.

**Comment by arjunptm** [comment]
I believe @rhnprabhune actually did something similar. Can you share the url of the hosted website?

**Comment by rhnprabhune** [comment]
http://rjprabhu.pythonanywhere.com/

**Comment by rhnprabhune** [comment]
![image](https://user-images.githubusercontent.com/51504486/144323559-8b51af5c-41fa-4e83-b136-570c5e9d46bc.png)
Getting an error on logging in/ signup window

**Comment by rhnprabhune** [comment]
In its free version PythonAnywhere is not able to access the RDS and it does not support other than https calls. Hence closing this issue. Moving it to future scope
